{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a51bff29-94f1-4212-b411-515e85aefff8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[Errno 2] No such file or directory: 'yolov5'\n",
      "/Users/dustinl/Documents/Projects/Signature-Detection-YOLO/yolov5\n",
      "Collecting matplotlib>=3.2.2\n",
      "  Downloading matplotlib-3.5.1-cp39-cp39-macosx_10_9_x86_64.whl (7.3 MB)\n",
      "\u001b[K     |████████████████████████████████| 7.3 MB 1.0 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting numpy>=1.18.5\n",
      "  Downloading numpy-1.22.3-cp39-cp39-macosx_10_14_x86_64.whl (17.6 MB)\n",
      "\u001b[K     |████████████████████████████████| 17.6 MB 3.5 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting opencv-python>=4.1.2\n",
      "  Using cached opencv_python-4.5.5.64-cp36-abi3-macosx_10_15_x86_64.whl (46.3 MB)\n",
      "Collecting Pillow>=7.1.2\n",
      "  Downloading Pillow-9.1.0-cp39-cp39-macosx_10_9_x86_64.whl (3.1 MB)\n",
      "\u001b[K     |████████████████████████████████| 3.1 MB 3.1 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting PyYAML>=5.3.1\n",
      "  Downloading PyYAML-6.0-cp39-cp39-macosx_10_9_x86_64.whl (197 kB)\n",
      "\u001b[K     |████████████████████████████████| 197 kB 3.2 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: requests>=2.23.0 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (2.27.1)\n",
      "Collecting scipy>=1.4.1\n",
      "  Downloading scipy-1.8.0-cp39-cp39-macosx_12_0_universal2.macosx_10_9_x86_64.whl (55.6 MB)\n",
      "\u001b[K     |████████████████████████████████| 55.6 MB 1.4 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting torch>=1.7.0\n",
      "  Downloading torch-1.11.0-cp39-none-macosx_10_9_x86_64.whl (129.9 MB)\n",
      "\u001b[K     |████████████████████████████████| 129.9 MB 1.0 MB/s eta 0:00:01   |▊                               | 2.8 MB 3.0 MB/s eta 0:00:43     |███████████▊                    | 47.7 MB 3.8 MB/s eta 0:00:22\n",
      "\u001b[?25hCollecting torchvision>=0.8.1\n",
      "  Downloading torchvision-0.12.0-cp39-cp39-macosx_10_9_x86_64.whl (1.2 MB)\n",
      "\u001b[K     |████████████████████████████████| 1.2 MB 558 kB/s eta 0:00:01\n",
      "\u001b[?25hCollecting tqdm>=4.41.0\n",
      "  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)\n",
      "Collecting tensorboard>=2.4.1\n",
      "  Using cached tensorboard-2.8.0-py3-none-any.whl (5.8 MB)\n",
      "Collecting pandas>=1.1.4\n",
      "  Downloading pandas-1.4.2-cp39-cp39-macosx_10_9_x86_64.whl (11.1 MB)\n",
      "\u001b[K     |████████████████████████████████| 11.1 MB 3.4 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting seaborn>=0.11.0\n",
      "  Using cached seaborn-0.11.2-py3-none-any.whl (292 kB)\n",
      "Collecting thop\n",
      "  Using cached thop-0.0.31.post2005241907-py3-none-any.whl (8.7 kB)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from matplotlib>=3.2.2->-r requirements.txt (line 4)) (2.8.2)\n",
      "Collecting cycler>=0.10\n",
      "  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)\n",
      "Collecting fonttools>=4.22.0\n",
      "  Using cached fonttools-4.33.3-py3-none-any.whl (930 kB)\n",
      "Requirement already satisfied: pyparsing>=2.2.1 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from matplotlib>=3.2.2->-r requirements.txt (line 4)) (3.0.4)\n",
      "Collecting kiwisolver>=1.0.1\n",
      "  Downloading kiwisolver-1.4.2-cp39-cp39-macosx_10_9_x86_64.whl (65 kB)\n",
      "\u001b[K     |████████████████████████████████| 65 kB 2.3 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: packaging>=20.0 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from matplotlib>=3.2.2->-r requirements.txt (line 4)) (21.3)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from requests>=2.23.0->-r requirements.txt (line 9)) (3.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from requests>=2.23.0->-r requirements.txt (line 9)) (2021.10.8)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from requests>=2.23.0->-r requirements.txt (line 9)) (1.26.9)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from requests>=2.23.0->-r requirements.txt (line 9)) (2.0.4)\n",
      "Requirement already satisfied: typing-extensions in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from torch>=1.7.0->-r requirements.txt (line 11)) (4.1.1)\n",
      "Requirement already satisfied: wheel>=0.26 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from tensorboard>=2.4.1->-r requirements.txt (line 16)) (0.37.1)\n",
      "Collecting werkzeug>=0.11.15\n",
      "  Downloading Werkzeug-2.1.2-py3-none-any.whl (224 kB)\n",
      "\u001b[K     |████████████████████████████████| 224 kB 1.4 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting protobuf>=3.6.0\n",
      "  Downloading protobuf-3.20.1-cp39-cp39-macosx_10_9_x86_64.whl (962 kB)\n",
      "\u001b[K     |████████████████████████████████| 962 kB 715 kB/s eta 0:00:01\n",
      "\u001b[?25hCollecting grpcio>=1.24.3\n",
      "  Downloading grpcio-1.44.0-cp39-cp39-macosx_10_10_x86_64.whl (4.3 MB)\n",
      "\u001b[K     |████████████████████████████████| 4.3 MB 1.9 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting google-auth<3,>=1.6.3\n",
      "  Using cached google_auth-2.6.6-py2.py3-none-any.whl (156 kB)\n",
      "Collecting google-auth-oauthlib<0.5,>=0.4.1\n",
      "  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)\n",
      "Collecting tensorboard-data-server<0.7.0,>=0.6.0\n",
      "  Using cached tensorboard_data_server-0.6.1-py3-none-macosx_10_9_x86_64.whl (3.5 MB)\n",
      "Collecting tensorboard-plugin-wit>=1.6.0\n",
      "  Using cached tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)\n",
      "Collecting absl-py>=0.4\n",
      "  Using cached absl_py-1.0.0-py3-none-any.whl (126 kB)\n",
      "Requirement already satisfied: setuptools>=41.0.0 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from tensorboard>=2.4.1->-r requirements.txt (line 16)) (61.2.0)\n",
      "Collecting markdown>=2.6.8\n",
      "  Using cached Markdown-3.3.6-py3-none-any.whl (97 kB)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from pandas>=1.1.4->-r requirements.txt (line 20)) (2021.3)\n",
      "Requirement already satisfied: six in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from absl-py>=0.4->tensorboard>=2.4.1->-r requirements.txt (line 16)) (1.16.0)\n",
      "Collecting cachetools<6.0,>=2.0.0\n",
      "  Using cached cachetools-5.0.0-py3-none-any.whl (9.1 kB)\n",
      "Collecting pyasn1-modules>=0.2.1\n",
      "  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)\n",
      "Collecting rsa<5,>=3.1.4\n",
      "  Using cached rsa-4.8-py3-none-any.whl (39 kB)\n",
      "Collecting requests-oauthlib>=0.7.0\n",
      "  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)\n",
      "Collecting importlib-metadata>=4.4\n",
      "  Using cached importlib_metadata-4.11.3-py3-none-any.whl (18 kB)\n",
      "Collecting zipp>=0.5\n",
      "  Using cached zipp-3.8.0-py3-none-any.whl (5.4 kB)\n",
      "Collecting pyasn1<0.5.0,>=0.4.6\n",
      "  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)\n",
      "Collecting oauthlib>=3.0.0\n",
      "  Using cached oauthlib-3.2.0-py3-none-any.whl (151 kB)\n",
      "Installing collected packages: pyasn1, zipp, rsa, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, Pillow, numpy, kiwisolver, importlib-metadata, google-auth, fonttools, cycler, werkzeug, torch, tensorboard-plugin-wit, tensorboard-data-server, scipy, protobuf, pandas, matplotlib, markdown, grpcio, google-auth-oauthlib, absl-py, tqdm, torchvision, thop, tensorboard, seaborn, PyYAML, opencv-python\n",
      "Successfully installed Pillow-9.1.0 PyYAML-6.0 absl-py-1.0.0 cachetools-5.0.0 cycler-0.11.0 fonttools-4.33.3 google-auth-2.6.6 google-auth-oauthlib-0.4.6 grpcio-1.44.0 importlib-metadata-4.11.3 kiwisolver-1.4.2 markdown-3.3.6 matplotlib-3.5.1 numpy-1.22.3 oauthlib-3.2.0 opencv-python-4.5.5.64 pandas-1.4.2 protobuf-3.20.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-oauthlib-1.3.1 rsa-4.8 scipy-1.8.0 seaborn-0.11.2 tensorboard-2.8.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 thop-0.0.31.post2005241907 torch-1.11.0 torchvision-0.12.0 tqdm-4.64.0 werkzeug-2.1.2 zipp-3.8.0\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%cd yolov5\n",
    "%pip install -r requirements.txt # install dependencies"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "f527ebbc-5f17-4bf0-a992-65fec9bea0dc",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Using cache found in /Users/dustinl/.cache/torch/hub/ultralytics_yolov5_master\n",
      "YOLOv5 🚀 2022-4-28 torch 1.11.0 CPU\n",
      "\n",
      "Fusing layers... \n",
      "YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients\n",
      "Adding AutoShape... \n",
      "Saved 1 image to \u001b[1mruns/detect/exp\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "image 1/1: 720x1280 2 persons, 2 ties\n",
      "Speed: 753.7ms pre-process, 203.6ms inference, 3.1ms NMS per image at shape (1, 3, 384, 640)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>xmin</th>\n",
       "      <th>ymin</th>\n",
       "      <th>xmax</th>\n",
       "      <th>ymax</th>\n",
       "      <th>confidence</th>\n",
       "      <th>class</th>\n",
       "      <th>name</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>743.290466</td>\n",
       "      <td>48.343597</td>\n",
       "      <td>1141.756592</td>\n",
       "      <td>720.000000</td>\n",
       "      <td>0.879860</td>\n",
       "      <td>0</td>\n",
       "      <td>person</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>441.989624</td>\n",
       "      <td>437.336670</td>\n",
       "      <td>496.585083</td>\n",
       "      <td>710.036255</td>\n",
       "      <td>0.675119</td>\n",
       "      <td>27</td>\n",
       "      <td>tie</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>123.051117</td>\n",
       "      <td>193.238037</td>\n",
       "      <td>714.690552</td>\n",
       "      <td>719.771301</td>\n",
       "      <td>0.666692</td>\n",
       "      <td>0</td>\n",
       "      <td>person</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>978.989807</td>\n",
       "      <td>313.579498</td>\n",
       "      <td>1025.302856</td>\n",
       "      <td>415.526154</td>\n",
       "      <td>0.261517</td>\n",
       "      <td>27</td>\n",
       "      <td>tie</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         xmin        ymin         xmax        ymax  confidence  class    name\n",
       "0  743.290466   48.343597  1141.756592  720.000000    0.879860      0  person\n",
       "1  441.989624  437.336670   496.585083  710.036255    0.675119     27     tie\n",
       "2  123.051117  193.238037   714.690552  719.771301    0.666692      0  person\n",
       "3  978.989807  313.579498  1025.302856  415.526154    0.261517     27     tie"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import torch\n",
    "\n",
    "# Model\n",
    "model = torch.hub.load('ultralytics/yolov5', 'yolov5s')\n",
    "\n",
    "# Images\n",
    "imgs = ['https://ultralytics.com/images/zidane.jpg']  # batch of images\n",
    "\n",
    "# Inference\n",
    "results = model(imgs)\n",
    "\n",
    "# Results\n",
    "results.print()\n",
    "results.save()  # or .show()\n",
    "\n",
    "results.xyxy[0]  # img1 predictions (tensor)\n",
    "results.pandas().xyxy[0]  # img1 predictions (pandas)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "3572feb0-6e04-4b82-8a36-38fbf8848b8d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[34m\u001b[1mtrain: \u001b[0mweights=yolov5s.pt, cfg=, data=coco128.yaml, hyp=data/hyps/hyp.scratch-low.yaml, epochs=3, batch_size=16, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest\n",
      "\u001b[34m\u001b[1mgithub: \u001b[0m⚠️ YOLOv5 is out of date by 1 commit. Use `git pull` or `git clone https://github.com/ultralytics/yolov5` to update.\n",
      "YOLOv5 🚀 v6.1-164-g177da7f torch 1.11.0 CPU\n",
      "\n",
      "\u001b[34m\u001b[1mhyperparameters: \u001b[0mlr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0\n",
      "\u001b[34m\u001b[1mWeights & Biases: \u001b[0mrun 'pip install wandb' to automatically track and visualize YOLOv5 🚀 runs (RECOMMENDED)\n",
      "\u001b[34m\u001b[1mTensorBoard: \u001b[0mStart with 'tensorboard --logdir runs/train', view at http://localhost:6006/\n",
      "\n",
      "                 from  n    params  module                                  arguments                     \n",
      "  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]              \n",
      "  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                \n",
      "  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   \n",
      "  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               \n",
      "  4                -1  2    115712  models.common.C3                        [128, 128, 2]                 \n",
      "  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              \n",
      "  6                -1  3    625152  models.common.C3                        [256, 256, 3]                 \n",
      "  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              \n",
      "  8                -1  1   1182720  models.common.C3                        [512, 512, 1]                 \n",
      "  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]                 \n",
      " 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              \n",
      " 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          \n",
      " 12           [-1, 6]  1         0  models.common.Concat                    [1]                           \n",
      " 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          \n",
      " 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              \n",
      " 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          \n",
      " 16           [-1, 4]  1         0  models.common.Concat                    [1]                           \n",
      " 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          \n",
      " 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              \n",
      " 19          [-1, 14]  1         0  models.common.Concat                    [1]                           \n",
      " 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          \n",
      " 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              \n",
      " 22          [-1, 10]  1         0  models.common.Concat                    [1]                           \n",
      " 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          \n",
      " 24      [17, 20, 23]  1    229245  models.yolo.Detect                      [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]\n",
      "Model summary: 270 layers, 7235389 parameters, 7235389 gradients, 16.5 GFLOPs\n",
      "\n",
      "Transferred 349/349 items from yolov5s.pt\n",
      "Scaled weight_decay = 0.0005\n",
      "\u001b[34m\u001b[1moptimizer:\u001b[0m SGD with parameter groups 57 weight (no decay), 60 weight, 60 bias\n",
      "\u001b[34m\u001b[1mtrain: \u001b[0mScanning '/Users/dustinl/Documents/Projects/Signature-Detection-YOLO/data\u001b[0m\n",
      "\u001b[34m\u001b[1mtrain: \u001b[0mNew cache created: /Users/dustinl/Documents/Projects/Signature-Detection-YOLO/datasets/coco128/labels/train2017.cache\n",
      "\u001b[34m\u001b[1mval: \u001b[0mScanning '/Users/dustinl/Documents/Projects/Signature-Detection-YOLO/datase\u001b[0m\n",
      "Plotting labels to runs/train/exp2/labels.jpg... \n",
      "\n",
      "\u001b[34m\u001b[1mAutoAnchor: \u001b[0m4.27 anchors/target, 0.994 Best Possible Recall (BPR). Current anchors are a good fit to dataset ✅\n",
      "Image sizes 640 train, 640 val\n",
      "Using 8 dataloader workers\n",
      "Logging results to \u001b[1mruns/train/exp2\u001b[0m\n",
      "Starting training for 3 epochs...\n",
      "\n",
      "     Epoch   gpu_mem       box       obj       cls    labels  img_size\n",
      "       0/2        0G   0.04552   0.06223   0.01816       260       640: 100%|███\n",
      "               Class     Images     Labels          P          R     mAP@.5 mAP@\n",
      "                 all        128        929      0.744      0.657      0.745       0.49\n",
      "\n",
      "     Epoch   gpu_mem       box       obj       cls    labels  img_size\n",
      "       1/2        0G   0.04399   0.06822   0.01675       210       640: 100%|███\n",
      "               Class     Images     Labels          P          R     mAP@.5 mAP@\n",
      "                 all        128        929      0.755      0.666      0.752        0.5\n",
      "\n",
      "     Epoch   gpu_mem       box       obj       cls    labels  img_size\n",
      "       2/2        0G   0.04441   0.06365   0.01595       269       640: 100%|███\n",
      "               Class     Images     Labels          P          R     mAP@.5 mAP@\n",
      "                 all        128        929      0.788      0.663      0.757       0.51\n",
      "\n",
      "3 epochs completed in 0.116 hours.\n",
      "Optimizer stripped from runs/train/exp2/weights/last.pt, 14.9MB\n",
      "Optimizer stripped from runs/train/exp2/weights/best.pt, 14.9MB\n",
      "\n",
      "Validating runs/train/exp2/weights/best.pt...\n",
      "Fusing layers... \n",
      "Model summary: 213 layers, 7225885 parameters, 0 gradients, 16.5 GFLOPs\n",
      "               Class     Images     Labels          P          R     mAP@.5 mAP@\n",
      "                 all        128        929      0.785      0.665      0.757      0.511\n",
      "              person        128        254      0.837      0.708       0.82      0.533\n",
      "             bicycle        128          6      0.795      0.667      0.768      0.444\n",
      "                 car        128         46      0.639      0.522      0.588      0.207\n",
      "          motorcycle        128          5      0.874        0.8      0.962       0.72\n",
      "            airplane        128          6      0.964          1      0.995      0.745\n",
      "                 bus        128          7      0.716      0.714      0.722      0.633\n",
      "               train        128          3          1      0.655      0.863      0.583\n",
      "               truck        128         12      0.544      0.417      0.539      0.309\n",
      "                boat        128          6      0.841      0.333      0.417      0.119\n",
      "       traffic light        128         14          1      0.257      0.427      0.235\n",
      "           stop sign        128          2      0.829          1      0.995      0.796\n",
      "               bench        128          9          1      0.512      0.705      0.286\n",
      "                bird        128         16        0.9          1      0.995      0.677\n",
      "                 cat        128          4      0.881          1      0.995      0.822\n",
      "                 dog        128          9          1      0.824      0.995      0.712\n",
      "               horse        128          2      0.787          1      0.995      0.647\n",
      "            elephant        128         17       0.96      0.882      0.939      0.708\n",
      "                bear        128          1      0.687          1      0.995      0.995\n",
      "               zebra        128          4      0.874          1      0.995      0.965\n",
      "             giraffe        128          9      0.998          1      0.995      0.618\n",
      "            backpack        128          6      0.886        0.5      0.709      0.341\n",
      "            umbrella        128         18      0.875      0.778        0.9      0.509\n",
      "             handbag        128         19          1      0.259      0.355      0.195\n",
      "                 tie        128          7      0.679      0.714      0.731      0.416\n",
      "            suitcase        128          4      0.889          1      0.995      0.597\n",
      "             frisbee        128          5      0.683        0.8      0.762      0.655\n",
      "                skis        128          1      0.641          1      0.995      0.497\n",
      "           snowboard        128          7      0.764      0.714      0.845      0.555\n",
      "         sports ball        128          6      0.711      0.667      0.603      0.307\n",
      "                kite        128         10      0.561        0.5      0.618      0.377\n",
      "        baseball bat        128          4      0.372       0.25      0.412      0.177\n",
      "      baseball glove        128          7      0.561      0.429      0.458      0.281\n",
      "          skateboard        128          5      0.721      0.532      0.613      0.462\n",
      "       tennis racket        128          7      0.647      0.571      0.578      0.319\n",
      "              bottle        128         18      0.697      0.513       0.68      0.352\n",
      "          wine glass        128         16      0.772          1      0.931        0.5\n",
      "                 cup        128         36      0.805      0.802      0.844      0.529\n",
      "                fork        128          6          1       0.33      0.459      0.307\n",
      "               knife        128         16      0.821      0.562      0.746      0.453\n",
      "               spoon        128         22      0.788      0.455      0.625      0.327\n",
      "                bowl        128         28      0.818      0.643      0.752      0.525\n",
      "              banana        128          1      0.678          1      0.995      0.398\n",
      "            sandwich        128          2          1          0      0.662      0.579\n",
      "              orange        128          4          1      0.957      0.995      0.699\n",
      "            broccoli        128         11      0.438      0.455      0.455      0.304\n",
      "              carrot        128         24      0.702      0.589       0.77      0.532\n",
      "             hot dog        128          2      0.564          1      0.828      0.762\n",
      "               pizza        128          5      0.796      0.784      0.928      0.677\n",
      "               donut        128         14      0.709          1      0.963      0.822\n",
      "                cake        128          4      0.859          1      0.995      0.852\n",
      "               chair        128         35      0.465      0.547      0.618      0.313\n",
      "               couch        128          6          1      0.662      0.752      0.538\n",
      "        potted plant        128         14      0.666      0.786      0.801      0.461\n",
      "                 bed        128          3      0.989      0.333      0.679      0.439\n",
      "        dining table        128         13      0.762      0.385      0.585      0.386\n",
      "              toilet        128          2      0.833          1      0.995      0.895\n",
      "                  tv        128          2      0.725          1      0.995      0.796\n",
      "              laptop        128          3          1          0       0.83      0.515\n",
      "               mouse        128          2          1          0     0.0792     0.0317\n",
      "              remote        128          8          1      0.617      0.659      0.533\n",
      "          cell phone        128          8      0.741       0.25      0.386      0.233\n",
      "           microwave        128          3      0.833          1      0.995      0.734\n",
      "                oven        128          5      0.547      0.495      0.598      0.336\n",
      "                sink        128          6       0.52      0.333      0.461      0.283\n",
      "        refrigerator        128          5      0.616        0.8      0.812       0.52\n",
      "                book        128         29       0.46      0.241      0.284      0.147\n",
      "               clock        128          9      0.762      0.889      0.961      0.708\n",
      "                vase        128          2      0.474          1      0.995       0.92\n",
      "            scissors        128          1          1          0      0.497      0.149\n",
      "          teddy bear        128         21      0.874      0.762      0.878      0.562\n",
      "          toothbrush        128          5       0.93          1      0.995      0.689\n",
      "Results saved to \u001b[1mruns/train/exp2\u001b[0m\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fba7027e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fba7027e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fba7027e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fba7027e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fba7027e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fba7027e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fba7027e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fba7027e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fed2031e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fba7027e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fed2031e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fba7027e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fed2031e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fed2031e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae5038d8b0>\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fed2031e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae5038d8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fed2031e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fed2031e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae5038d8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fed2031e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae5038d8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fed2031e8b0>\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae5038d8b0>\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fed2031e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae5038d8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae5038d8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae5038d8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae5038d8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae5038d8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbbc83658b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbbc83658b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbbc83658b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbbc83658b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbbc83658b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbbc83658b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbbc83658b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbbc83658b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbbc83658b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbbc83658b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc3608868b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc3608868b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc3608868b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc3608868b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc3608868b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc3608868b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc3608868b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc3608868b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc3608868b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc3608868b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd01831e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd01831e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd01831e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd01831e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd01831e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd01831e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd01831e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd01831e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae580b68b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd01831e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd01831e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae580b68b0>\n",
      "Traceback (most recent call last):\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae580b68b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae580b68b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae580b68b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae580b68b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae580b68b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae580b68b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae580b68b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fae580b68b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd8302968b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd8302968b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd8302968b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd8302968b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd8302968b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd8302968b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd8302968b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd8302968b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd8302968b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd8302968b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fcef02d58b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fcef02d58b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fcef02d58b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fcef02d58b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fcef02d58b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fcef02d58b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f9d702a68b0>\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fcef02d58b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fcef02d58b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f9d702a68b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8dc82ce8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f906830e8b0>\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f9d702a68b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f9d702a68b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f906830e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttrException ignored in: <function StorageWeakRef.__del__ at 0x7fbe6858e8b0>\n",
      "ibuteError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f9d702a68b0>\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8dc82ce8b0>\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f906830e8b0>\n",
      "reductions.py\", line 36, in __del__\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f906830e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbe6858e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f9d702a68b0>\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8dc82ce8b0>\n",
      "Traceback (most recent call last):\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f906830e8b0>\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbe6858e8b0>\n",
      "envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f9d702a68b0>\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f906830e8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbe6858e8b0>\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f9d702a68b0>\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8dc82ce8b0>\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakReException ignored in: <function StorageWeakRef.__del__ at 0x7f92d020f8b0>\n",
      "Traceback (most recent call last):\n",
      "f.__del__ at 0x7f7bf84258b0>\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbe6858e8b0>\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeException ignored in: <function StorageWeakRef.__del__ at 0x7fbe6858e8b0>\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8dc82ce8b0>\n",
      "Error: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Traceback (most recent call last):\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f92d020f8b0>\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ig  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "nored in: <function StorageWeakRef.__del__ at 0x7f906830e8b0>\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbe6858e8b0>\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Traceback (most recent call last):\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f7bf84258b0>\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f92d020f8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8dc82ce8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f7bf84258b0>\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fbe6858e8b0>\n",
      "lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f92d020f8b0>\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "AttributeErro  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "r: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8dc82ce8b0>\n",
      "Traceback (most recent call last):\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f92d020f8b0>\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f906830e8b0Traceback (most recent call last):\n",
      ">\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f7bf84258b0>\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f92d020f8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8dc82ce8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f92d020f8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f7bf84258b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductiAttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "ons.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd4103d58b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f92d020f8b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "AttributeError: 'NoneType' object has no attribute '_free_w  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "eak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f7bf84258b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f7bf84258b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd4103d58b0>\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f7bf84258b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd4103d58b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd4103d58b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd4103d58b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd4103d58b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd4103d58b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fd4103d58b0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7f8b98b4f280>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\n",
      "  File \"/Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages/torch/storage.py\", line 520, in _free_weak_ref\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\n"
     ]
    }
   ],
   "source": [
    "!python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "c1e9f8c7-ae27-4e5c-8d79-d12c45c9478e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting wandb\n",
      "  Downloading wandb-0.12.15-py2.py3-none-any.whl (1.8 MB)\n",
      "\u001b[K     |████████████████████████████████| 1.8 MB 3.0 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: python-dateutil>=2.6.1 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from wandb) (2.8.2)\n",
      "Collecting pathtools\n",
      "  Downloading pathtools-0.1.2.tar.gz (11 kB)\n",
      "Collecting sentry-sdk>=1.0.0\n",
      "  Downloading sentry_sdk-1.5.10-py2.py3-none-any.whl (144 kB)\n",
      "\u001b[K     |████████████████████████████████| 144 kB 3.0 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: PyYAML in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from wandb) (6.0)\n",
      "Collecting GitPython>=1.0.0\n",
      "  Using cached GitPython-3.1.27-py3-none-any.whl (181 kB)\n",
      "Collecting shortuuid>=0.5.0\n",
      "  Downloading shortuuid-1.0.8-py3-none-any.whl (9.5 kB)\n",
      "Requirement already satisfied: protobuf>=3.12.0 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from wandb) (3.20.1)\n",
      "Collecting docker-pycreds>=0.4.0\n",
      "  Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)\n",
      "Requirement already satisfied: requests<3,>=2.0.0 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from wandb) (2.27.1)\n",
      "Collecting Click!=8.0.0,>=7.0\n",
      "  Downloading click-8.1.3-py3-none-any.whl (96 kB)\n",
      "\u001b[K     |████████████████████████████████| 96 kB 3.2 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: six>=1.13.0 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from wandb) (1.16.0)\n",
      "Collecting psutil>=5.0.0\n",
      "  Downloading psutil-5.9.0-cp39-cp39-macosx_10_9_x86_64.whl (238 kB)\n",
      "\u001b[K     |████████████████████████████████| 238 kB 3.1 MB/s eta 0:00:01\n",
      "\u001b[?25hCollecting setproctitle\n",
      "  Downloading setproctitle-1.2.3-cp39-cp39-macosx_10_9_x86_64.whl (10 kB)\n",
      "Collecting promise<3,>=2.0\n",
      "  Downloading promise-2.3.tar.gz (19 kB)\n",
      "Collecting gitdb<5,>=4.0.1\n",
      "  Using cached gitdb-4.0.9-py3-none-any.whl (63 kB)\n",
      "Collecting smmap<6,>=3.0.1\n",
      "  Using cached smmap-5.0.0-py3-none-any.whl (24 kB)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from requests<3,>=2.0.0->wandb) (2.0.4)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from requests<3,>=2.0.0->wandb) (1.26.9)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from requests<3,>=2.0.0->wandb) (2021.10.8)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/dustinl/opt/anaconda3/envs/yolov5/lib/python3.9/site-packages (from requests<3,>=2.0.0->wandb) (3.3)\n",
      "Building wheels for collected packages: promise, pathtools\n",
      "  Building wheel for promise (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for promise: filename=promise-2.3-py3-none-any.whl size=21503 sha256=01bce5ffaa0663d58ecf45764bbf51d09cb8eadb4b46de9124bfe452da7016b9\n",
      "  Stored in directory: /Users/dustinl/Library/Caches/pip/wheels/e1/e8/83/ddea66100678d139b14bc87692ece57c6a2a937956d2532608\n",
      "  Building wheel for pathtools (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for pathtools: filename=pathtools-0.1.2-py3-none-any.whl size=8806 sha256=1de16c38779892eb992ced71a05c2414748a63de448ab6a46492ccee64ed93ac\n",
      "  Stored in directory: /Users/dustinl/Library/Caches/pip/wheels/b7/0a/67/ada2a22079218c75a88361c0782855cc72aebc4d18d0289d05\n",
      "Successfully built promise pathtools\n",
      "Installing collected packages: smmap, gitdb, shortuuid, setproctitle, sentry-sdk, psutil, promise, pathtools, GitPython, docker-pycreds, Click, wandb\n",
      "Successfully installed Click-8.1.3 GitPython-3.1.27 docker-pycreds-0.4.0 gitdb-4.0.9 pathtools-0.1.2 promise-2.3 psutil-5.9.0 sentry-sdk-1.5.10 setproctitle-1.2.3 shortuuid-1.0.8 smmap-5.0.0 wandb-0.12.15\n"
     ]
    }
   ],
   "source": [
    "!pip install wandb"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
